---
title: "About"
description: |
  A paddle log
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

This is a personal paddle log to collate my paddling reports and reflect on personal development.

### Map

Zoom to see where I've paddled (so far...)

```{r, echo = FALSE}
library("leaflet")
paddles = sf::st_read("R/paddles.shp", quiet = TRUE)
leaflet(paddles) %>%
  addProviderTiles(provider = "Stamen.Watercolor") %>%
  addPolylines(weight = 5,
               color = "purple", 
               opacity = 1, 
               label = ~name) %>%
  setView(-2.74978, 54.07527, zoom = 7) %>%
  leaflet.extras::addFullscreenControl()

```

### Clubs

I currently paddle with a number of local clubs:

- [Lancaster & District Canoe Club](https://www.ldcc.club/)
- [Lakeland Canoe Club](https://lakelandcanoeclub.wordpress.com/)
- [Ulverston Canoe Club](https://www.ulverstoncc.org/)
- [Cumbria Canoeists](https://www.cumbriacanoeists.org.uk/)

### Qualifications

- Paddlesport Instuctor (Kayak)
- FSRT
- VHF SRC
- CNTP
